Traceback (most recent call last):
  File "<pyshell#14>", line 2, in <module>
Exception: Error.com
Traceback (most recent call last):
  File "<pyshell#17>", line 2, in <module>
Exception: Error.com
